name: CI

on: push

jobs:
  run:
    name: Lint and run
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: pip install -r requirements.txt -r requirements_dev.txt
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: 1
        PIP_PROGRESS_BAR: "off"

    - name: Lint
      run: pylint tamuro.py

    - name: Typecheck
      run: mypy tamuro.py

    - name: Run
      run: python tamuro.py
